---
- name: Create directory for Gitlab
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /srv/gitlab/
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs

- name: Add docker-compouse.yml
  template:
    src: docker-compose.yml.j2
    dest: /srv/gitlab/docker-compose.yml