---
# tasks file for app

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name:
  template:
    src: db_config.j2
    dest: /opt/reddit/db_config
    owner: appuser
    group: appuser

- name: enable puma
  systemd: 
    name: puma
    enabled: yes