- name: Configure MongoDB 
  hosts: db
  tags: db-tag
  become: yes

  vars:
    mongo_bind_ip: 0.0.0.0
    
  tasks:
    - name: Change mongo config file
      template:
        src: ./templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configure App
  hosts: app
  tags: app-tag
  become: true

  vars: 
    db_host: 10.156.0.45

  tasks: 

    - name: Add unit file for Puma
      copy:
        src: ./files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name:
      template:
        src: templates/db_config.j2
        dest: /opt/reddit/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: 
        name: puma
        enabled: yes
    
  handlers:

    - name: reload puma
      systemd: 
        name: puma
        state: reloaded

- name: Deploy App
  hosts: app
  tags: app-tag
  become: true

  vars: 
    db_host: 10.156.0.45

  tasks:
  - name: Fetch the latest version of applocatiob code
    git:
      repo: 'https://github.com/Artemmkin/raddit.git'
      dest: /opt/reddit
      force: yes

  - name: Change puma db setting
    shell: sed -i 's/127.0.0.1/{{ db_host }}/g' /opt/reddit/app.rb
    tags: deploy-tag
    notify: restart puma

  handlers:
  - name: restart puma
    become: true
    systemd:
      name: puma
      state: restarted
