- name: "Reddit App: Install mongodb"
  hosts: db
  become: yes
  gather_facts: no

  vars: 
    mongo_bind_ip: 0.0.0.0

  tasks:
  - name: Added mongodb package
    shell: 'echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'
  
  - name: Install mongodb package    
    apt:
      name: mongodb-org
      state: present
      update_cache: yes
      allow_unauthenticated: yes

  - name: Change mongo config file
    become: true
    template:
      src: ./templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644

  - name: Enable and start Mongo DB service
    systemd:
      name: mongod
      enabled: yes
      state: started