- name: Deploy App
  hosts: app
  become: true

  tasks:
  - name: Fetch the latest version of applocatiob code
    git:
      repo: 'https://github.com/Artemmkin/raddit.git'
      dest: /opt/reddit
      force: yes
    notify: restart puma

  - name: bundle install
    bundler:
      state: present
      chdir: /opt/reddit
      user_install: no
    notify: restart puma

  - name: Change puma db setting
    shell: sed -i 's/127.0.0.1/{{ db_host }}/g' /opt/reddit/app.rb
    tags: deploy-tag
    notify: restart puma

  handlers:
  - name: restart puma
    become: true
    systemd:
      name: puma
      state: restarted
