tasks:
  - name: Add an apt key by id from keyserver
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
      filename: docker
  
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install docker & docker-compose
    apt: 
      name:
        - docker-ce
        - docker-compose
      state: present
      update_cache: yes