- name: Install Gitlab-CI
  hosts: all
  tags: all
  become:  True
  
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
  
  roles:
    - role: docker
    - role: gitlab

  tasks:
    - name: Run docker-compose
      shell: cd /srv/gitlab && docker-compose up -d