- name: "Reddit App: Congfigure app environment"
  hosts: app
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: app
  gather_facts: no

  tasks:
  - name: Create folder for git clone
    become: yes
    file:
      state: directory
      dest: /opt/reddit
      owner: appuser

  - name: Clone git repo
    git:
      repo: 'https://github.com/Artemmkin/raddit.git'
      dest: /opt/reddit

  - name: Bundle install
    bundler:
      state: present
      chdir: /opt/reddit
      user_install: no

  - name: Copy puma service file
    become: yes
    copy:
      src: ./puma.service
      dest: /etc/systemd/system

  - name: Enable and start puma service
    become: yes
    systemd:
      name: puma
      enabled: yes
      state: started
  